// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBW-MoTttcXT7ge8bo3wNpeXoHzjSrlM5Y',
    appId: '1:494588817221:web:e09942e141a6f1e1df182c',
    messagingSenderId: '494588817221',
    projectId: 'partychu-30c24',
    authDomain: 'partychu-30c24.firebaseapp.com',
    storageBucket: 'partychu-30c24.firebasestorage.app',
    measurementId: 'G-3J6CZ02T7Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOeBA3K6T_PQF56xirshTalwGpdsHxdpY',
    appId: '1:494588817221:android:4af49b9d5f39c069df182c',
    messagingSenderId: '494588817221',
    projectId: 'partychu-30c24',
    storageBucket: 'partychu-30c24.firebasestorage.app',
  );

  // ios/Runner/GoogleService-Info.plist(BUNDLE_ID = com.partychu.app)와
  // 값을 맞춘 것이다. plist를 다시 받으면 여기도 같이 맞춰야 한다 —
  // appId(GOOGLE_APP_ID)와 iosClientId(CLIENT_ID)가 특히 앱마다 다르다.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpyekuODrDStBm9MDmLx_19lZLFl6i4cI',
    appId: '1:494588817221:ios:d7f8bd9221b4a9e7df182c',
    messagingSenderId: '494588817221',
    projectId: 'partychu-30c24',
    storageBucket: 'partychu-30c24.firebasestorage.app',
    iosClientId:
        '494588817221-dfm6v76vqdcn5duvkoath9k1kk9sa51q.apps.googleusercontent.com',
    iosBundleId: 'com.partychu.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpyekuODrDStBm9MDmLx_19lZLFl6i4cI',
    appId: '1:494588817221:ios:48883b3367b25ab3df182c',
    messagingSenderId: '494588817221',
    projectId: 'partychu-30c24',
    storageBucket: 'partychu-30c24.firebasestorage.app',
    iosBundleId: 'com.partychu.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBW-MoTttcXT7ge8bo3wNpeXoHzjSrlM5Y',
    appId: '1:494588817221:web:0fdda55cc394d8f5df182c',
    messagingSenderId: '494588817221',
    projectId: 'partychu-30c24',
    authDomain: 'partychu-30c24.firebaseapp.com',
    storageBucket: 'partychu-30c24.firebasestorage.app',
    measurementId: 'G-ZPEGY00DJG',
  );
}
