import 'package:flutter/material.dart';
import 'package:party_app/widgets/party_form/custom_time_picker_sheet.dart';
import 'package:party_app/widgets/party_form/date_time_sheet.dart'
    show formatPartyDate, formatPartyTime;

const _kAccent = Color(0xFFFF6FA0);
const _kBoxFill = Color(0xFFF7F7FA);

/// 매주 반복으로 자동 생성 가능한 최대 회차 — 약 1년치.
const kWeeklyRepeatMaxOccurrences = 52;

/// 날짜 슬롯 하나 — 파티가 여러 날짜에 걸쳐 열릴 때 각 날짜(+시간)를 나타낸다.
/// [id]는 리스트 아이템 위젯 키/추적용 안정 식별자일 뿐 Firestore에는
/// 저장되지 않는다. index 0 슬롯이 항상 "기준"이며(매주 반복의 기준 날짜,
/// 수정 모드에서 기존 문서를 업데이트하는 슬롯), 리스트는 자동 정렬하지
/// 않는다 — 정렬로 인해 기준이 의도치 않게 바뀌는 걸 막기 위함.
class PartyDateSlot {
  final String id;
  final DateTime date;
  final TimeOfDay? startTime;
  final TimeOfDay? endTime;
  /// true면 "매주 반복"으로 자동 생성된 날짜.
  final bool isAutoGenerated;

  const PartyDateSlot({
    required this.id,
    required this.date,
    this.startTime,
    this.endTime,
    this.isAutoGenerated = false,
  });

  PartyDateSlot copyWith({
    DateTime? date,
    TimeOfDay? startTime,
    bool clearStartTime = false,
    TimeOfDay? endTime,
    bool clearEndTime = false,
    bool? isAutoGenerated,
  }) {
    return PartyDateSlot(
      id: id,
      date: date ?? this.date,
      startTime: clearStartTime ? null : (startTime ?? this.startTime),
      endTime: clearEndTime ? null : (endTime ?? this.endTime),
      isAutoGenerated: isAutoGenerated ?? this.isAutoGenerated,
    );
  }
}

int _slotIdCounter = 0;

/// 새 슬롯 id 발급 — 등록/수정 화면의 prefill 복원 시에도 이 함수를 그대로 쓴다.
String newPartyDateSlotId() =>
    'slot_${DateTime.now().microsecondsSinceEpoch}_${_slotIdCounter++}';

String _isoDate(DateTime d) =>
    '${d.year.toString().padLeft(4, '0')}-${d.month.toString().padLeft(2, '0')}-${d.day.toString().padLeft(2, '0')}';

/// [anchorDate] 다음 주부터 매주 같은 요일로 날짜를 생성한다(anchorDate
/// 자체는 포함하지 않음 — 그건 이미 슬롯 0으로 존재한다).
/// - endDate/count 둘 다 없으면 빈 리스트(= 아직 아무 것도 생성하지 않음).
/// - 둘 다 있으면 먼저 도달하는 조건에서 멈춘다.
/// - count는 "추가로 몇 번 더" 생성할지(anchor 제외) 의미.
/// - excludedIsoDates와 겹치면 건너뛰되, count를 채우기 위해 계속 다음
///   주로 진행한다(제외된 날짜가 count 자리를 차지하지 않음).
/// - [maxOccurrences]는 count가 아무리 커도 넘지 않는 하드 캡.
List<DateTime> computeWeeklyRepeatDates({
  required DateTime anchorDate,
  DateTime? endDate,
  int? count,
  Set<String> excludedIsoDates = const {},
  int maxOccurrences = kWeeklyRepeatMaxOccurrences,
}) {
  if (endDate == null && count == null) return [];
  final result = <DateTime>[];
  var cursor = DateTime(
    anchorDate.year,
    anchorDate.month,
    anchorDate.day,
  ).add(const Duration(days: 7));
  final endDay = endDate == null
      ? null
      : DateTime(endDate.year, endDate.month, endDate.day);
  // excludedIsoDates가 아무리 많아도(예: 전부 제외) 무한루프에 빠지지
  // 않도록 시도 횟수 자체에도 별도의 하드 캡을 둔다.
  var iterations = 0;
  final maxIterations = maxOccurrences * 4;
  while (iterations < maxIterations) {
    iterations++;
    if (result.length >= maxOccurrences) break;
    if (count != null && result.length >= count) break;
    if (endDay != null && cursor.isAfter(endDay)) break;
    if (!excludedIsoDates.contains(_isoDate(cursor))) {
      result.add(cursor);
    }
    cursor = cursor.add(const Duration(days: 7));
  }
  return result;
}

/// 날짜 목록 시트가 입출력하는 값. 화면(party_register_screen.dart)의 여러
/// state 필드를 하나로 묶어 시트에 넘기고, 시트를 닫을 때 통째로 돌려받는
/// 경계용 DTO.
class PartyDateListDraft {
  final List<PartyDateSlot> slots;
  final TimeOfDay? recruitDeadlineTime;
  final bool weeklyRepeatEnabled;
  final DateTime? weeklyRepeatEndDate;
  final int? weeklyRepeatCount;
  /// 사용자가 명시적으로 지운 자동생성 날짜(ISO 'yyyy-MM-dd') — 반복 설정을
  /// 껐다 켜거나 종료일/횟수를 바꿔도 이 날짜들은 되살아나지 않는다.
  final Set<String> weeklyRepeatExcludedDates;

  const PartyDateListDraft({
    this.slots = const [],
    this.recruitDeadlineTime,
    this.weeklyRepeatEnabled = false,
    this.weeklyRepeatEndDate,
    this.weeklyRepeatCount,
    this.weeklyRepeatExcludedDates = const {},
  });
}

Future<PartyDateListDraft?> showPartyDateListSheet(
  BuildContext context, {
  required PartyDateListDraft initial,
}) {
  return showModalBottomSheet<PartyDateListDraft>(
    context: context,
    isScrollControlled: true,
    backgroundColor: Colors.white,
    shape: const RoundedRectangleBorder(
      borderRadius: BorderRadius.vertical(top: Radius.circular(20)),
    ),
    builder: (_) => _PartyDateListSheetBody(initial: initial),
  );
}

class _PartyDateListSheetBody extends StatefulWidget {
  final PartyDateListDraft initial;

  const _PartyDateListSheetBody({required this.initial});

  @override
  State<_PartyDateListSheetBody> createState() =>
      _PartyDateListSheetBodyState();
}

class _PartyDateListSheetBodyState extends State<_PartyDateListSheetBody> {
  final List<PartyDateSlot> _slots = [];
  late TimeOfDay? _recruitDeadlineTime = widget.initial.recruitDeadlineTime;
  late bool _weeklyRepeatEnabled = widget.initial.weeklyRepeatEnabled;
  late DateTime? _weeklyRepeatEndDate = widget.initial.weeklyRepeatEndDate;
  late int? _weeklyRepeatCount = widget.initial.weeklyRepeatCount;
  final Set<String> _weeklyRepeatExcludedDates = {};
  late final _repeatCountController = TextEditingController(
    text: _weeklyRepeatCount?.toString() ?? '',
  );

  @override
  void initState() {
    super.initState();
    _slots.addAll(widget.initial.slots);
    _weeklyRepeatExcludedDates.addAll(widget.initial.weeklyRepeatExcludedDates);
  }

  @override
  void dispose() {
    _repeatCountController.dispose();
    super.dispose();
  }

  DateTime get _today {
    final now = DateTime.now();
    return DateTime(now.year, now.month, now.day);
  }

  void _regenerateAutoSlots() {
    setState(() {
      _slots.removeWhere((s) => s.isAutoGenerated);
      if (!_weeklyRepeatEnabled || _slots.isEmpty) return;
      final anchor = _slots.first;
      final otherDates = _slots.map((s) => _isoDate(s.date)).toSet();
      final generated = computeWeeklyRepeatDates(
        anchorDate: anchor.date,
        endDate: _weeklyRepeatEndDate,
        count: _weeklyRepeatCount,
        excludedIsoDates: {..._weeklyRepeatExcludedDates, ...otherDates},
      );
      for (final d in generated) {
        _slots.add(
          PartyDateSlot(
            id: newPartyDateSlotId(),
            date: d,
            startTime: anchor.startTime,
            endTime: anchor.endTime,
            isAutoGenerated: true,
          ),
        );
      }
    });
  }

  Future<void> _addDateSlot() async {
    final last = _slots.isNotEmpty ? _slots.last.date : null;
    final initial = last != null
        ? last.add(const Duration(days: 1))
        : _today;
    final picked = await showDatePicker(
      context: context,
      initialDate: initial.isBefore(_today) ? _today : initial,
      firstDate: _today,
      lastDate: DateTime(_today.year + 3),
    );
    if (picked == null) return;
    final wasEmpty = _slots.isEmpty;
    setState(() {
      _slots.add(
        PartyDateSlot(id: newPartyDateSlotId(), date: picked),
      );
    });
    if (wasEmpty && _weeklyRepeatEnabled) _regenerateAutoSlots();
  }

  /// 자동생성 슬롯을 사용자가 직접 수정하면 수동 슬롯으로 승격한다. 날짜가
  /// 바뀐 경우 원래 생성됐던 날짜를 제외 목록에 남겨 재계산 시 되살아나지
  /// 않게 한다.
  void _promoteIfAutoGenerated(int index, {DateTime? newDate}) {
    final slot = _slots[index];
    if (!slot.isAutoGenerated) return;
    if (newDate != null) {
      _weeklyRepeatExcludedDates.add(_isoDate(slot.date));
    }
    _slots[index] = slot.copyWith(isAutoGenerated: false);
  }

  Future<void> _pickSlotDate(int index) async {
    final slot = _slots[index];
    final initial = slot.date.isBefore(_today) ? _today : slot.date;
    final picked = await showDatePicker(
      context: context,
      initialDate: initial,
      firstDate: _today,
      lastDate: DateTime(_today.year + 3),
    );
    if (picked == null) return;
    setState(() {
      _promoteIfAutoGenerated(index, newDate: picked);
      _slots[index] = _slots[index].copyWith(date: picked);
      if (index == 0 && _weeklyRepeatEnabled) _regenerateAutoSlots();
    });
  }

  Future<void> _pickSlotStartTime(int index) async {
    final slot = _slots[index];
    final picked = await showCustomTimePicker(
      context,
      initial: slot.startTime ?? const TimeOfDay(hour: 20, minute: 0),
      title: '시작 시간',
    );
    if (picked == null) return;
    setState(() {
      _promoteIfAutoGenerated(index);
      _slots[index] = _slots[index].copyWith(startTime: picked);
    });
  }

  Future<void> _pickSlotEndTime(int index) async {
    final slot = _slots[index];
    final picked = await showCustomTimePicker(
      context,
      initial: slot.endTime ?? const TimeOfDay(hour: 23, minute: 0),
      title: '종료 시간',
    );
    if (picked == null) return;
    setState(() {
      _promoteIfAutoGenerated(index);
      _slots[index] = _slots[index].copyWith(endTime: picked);
    });
  }

  void _deleteSlot(int index) {
    setState(() {
      final slot = _slots.removeAt(index);
      if (slot.isAutoGenerated) {
        _weeklyRepeatExcludedDates.add(_isoDate(slot.date));
      }
    });
  }

  void _toggleWeeklyRepeat(bool v) {
    setState(() => _weeklyRepeatEnabled = v);
    _regenerateAutoSlots();
  }

  Future<void> _pickWeeklyEndDate() async {
    final base = _weeklyRepeatEndDate ?? _today;
    final picked = await showDatePicker(
      context: context,
      initialDate: base.isBefore(_today) ? _today : base,
      firstDate: _today,
      lastDate: DateTime(_today.year + 3),
    );
    if (picked == null) return;
    setState(() => _weeklyRepeatEndDate = picked);
    _regenerateAutoSlots();
  }

  void _clearWeeklyEndDate() {
    setState(() => _weeklyRepeatEndDate = null);
    _regenerateAutoSlots();
  }

  void _onRepeatCountChanged(String text) {
    final parsed = int.tryParse(text.trim());
    if (parsed == null) {
      setState(() => _weeklyRepeatCount = null);
      _regenerateAutoSlots();
      return;
    }
    final clamped = parsed > kWeeklyRepeatMaxOccurrences
        ? kWeeklyRepeatMaxOccurrences
        : parsed;
    if (clamped != parsed) {
      _repeatCountController.text = clamped.toString();
      _repeatCountController.selection = TextSelection.collapsed(
        offset: _repeatCountController.text.length,
      );
    }
    setState(() => _weeklyRepeatCount = clamped);
    _regenerateAutoSlots();
  }

  Future<void> _pickRecruitDeadlineTime() async {
    final picked = await showCustomTimePicker(
      context,
      initial: _recruitDeadlineTime ?? const TimeOfDay(hour: 18, minute: 0),
      title: '모집 마감 시간',
    );
    if (picked == null) return;
    setState(() => _recruitDeadlineTime = picked);
  }

  void _clearDeadline() {
    setState(() => _recruitDeadlineTime = null);
  }

  Widget _label(String text) => Padding(
    padding: const EdgeInsets.only(bottom: 8),
    child: Text(
      text,
      style: const TextStyle(fontSize: 14, fontWeight: FontWeight.w600),
    ),
  );

  Widget _box(
    String text,
    VoidCallback onTap, {
    bool hasValue = false,
  }) => InkWell(
    onTap: onTap,
    borderRadius: BorderRadius.circular(12),
    child: Container(
      width: double.infinity,
      padding: const EdgeInsets.all(14),
      decoration: BoxDecoration(
        color: _kBoxFill,
        borderRadius: BorderRadius.circular(12),
      ),
      child: Text(
        text,
        style: TextStyle(color: hasValue ? Colors.black87 : Colors.black38),
        overflow: TextOverflow.ellipsis,
      ),
    ),
  );

  Widget _slotCard(int index) {
    final slot = _slots[index];
    final isAnchor = index == 0;
    return Container(
      margin: const EdgeInsets.only(bottom: 10),
      padding: const EdgeInsets.all(12),
      decoration: BoxDecoration(
        color: const Color(0xFFFAFAFC),
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: const Color(0xFFE8EBF2)),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              Text(
                '날짜 ${index + 1}',
                style: const TextStyle(
                  fontSize: 13,
                  fontWeight: FontWeight.bold,
                  color: _kAccent,
                ),
              ),
              if (isAnchor && _weeklyRepeatEnabled) ...[
                const SizedBox(width: 6),
                Container(
                  padding: const EdgeInsets.symmetric(
                    horizontal: 6,
                    vertical: 2,
                  ),
                  decoration: BoxDecoration(
                    color: _kAccent.withValues(alpha: 0.12),
                    borderRadius: BorderRadius.circular(6),
                  ),
                  child: const Text(
                    '기준',
                    style: TextStyle(
                      fontSize: 11,
                      color: _kAccent,
                      fontWeight: FontWeight.w600,
                    ),
                  ),
                ),
              ],
              if (slot.isAutoGenerated) ...[
                const SizedBox(width: 6),
                Container(
                  padding: const EdgeInsets.symmetric(
                    horizontal: 6,
                    vertical: 2,
                  ),
                  decoration: BoxDecoration(
                    color: const Color(0xFFF0F4FF),
                    borderRadius: BorderRadius.circular(6),
                  ),
                  child: const Text(
                    '반복 생성됨',
                    style: TextStyle(
                      fontSize: 11,
                      color: Color(0xFF4A63C8),
                      fontWeight: FontWeight.w600,
                    ),
                  ),
                ),
              ],
              const Spacer(),
              IconButton(
                onPressed: () => _deleteSlot(index),
                icon: const Icon(Icons.delete_outline, size: 20),
                color: Colors.redAccent,
                padding: EdgeInsets.zero,
                constraints: const BoxConstraints(minWidth: 28, minHeight: 28),
              ),
            ],
          ),
          const SizedBox(height: 6),
          _box(
            formatPartyDate(slot.date),
            () => _pickSlotDate(index),
            hasValue: true,
          ),
          const SizedBox(height: 8),
          Row(
            children: [
              Expanded(
                child: _box(
                  formatPartyTime(slot.startTime),
                  () => _pickSlotStartTime(index),
                  hasValue: slot.startTime != null,
                ),
              ),
              const SizedBox(width: 8),
              Expanded(
                child: _box(
                  formatPartyTime(slot.endTime),
                  () => _pickSlotEndTime(index),
                  hasValue: slot.endTime != null,
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    final hasDeadline = _recruitDeadlineTime != null;

    return SafeArea(
      child: ConstrainedBox(
        constraints: BoxConstraints(
          maxHeight: MediaQuery.of(context).size.height * 0.88,
        ),
        child: Padding(
          padding: EdgeInsets.only(
            left: 20,
            right: 20,
            top: 16,
            bottom: 16 + MediaQuery.of(context).viewInsets.bottom,
          ),
          child: SingleChildScrollView(
            child: Column(
              mainAxisSize: MainAxisSize.min,
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Center(
                  child: Container(
                    width: 40,
                    height: 4,
                    decoration: BoxDecoration(
                      color: Colors.grey.shade300,
                      borderRadius: BorderRadius.circular(4),
                    ),
                  ),
                ),
                const SizedBox(height: 16),
                const Text(
                  '날짜 및 시간 선택',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
                ),
                const SizedBox(height: 18),
                if (_slots.isEmpty)
                  const Padding(
                    padding: EdgeInsets.only(bottom: 8),
                    child: Text(
                      '날짜를 하나 이상 추가해주세요. 서로 다른 날짜를 여러 개 추가할 수 있어요.',
                      style: TextStyle(fontSize: 12, color: Colors.black45),
                    ),
                  ),
                ...List.generate(_slots.length, _slotCard),
                GestureDetector(
                  onTap: _addDateSlot,
                  child: Container(
                    margin: const EdgeInsets.only(bottom: 20),
                    padding: const EdgeInsets.symmetric(vertical: 12),
                    decoration: BoxDecoration(
                      color: const Color(0xFFFFF3F7),
                      borderRadius: BorderRadius.circular(10),
                      border: Border.all(color: _kAccent.withValues(alpha: 0.3)),
                    ),
                    child: const Row(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: [
                        Icon(Icons.add, size: 16, color: _kAccent),
                        SizedBox(width: 4),
                        Text(
                          '날짜 추가',
                          style: TextStyle(
                            fontSize: 13,
                            color: _kAccent,
                            fontWeight: FontWeight.w600,
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
                Row(
                  children: [
                    const Expanded(
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Text(
                            '매주 반복',
                            style: TextStyle(
                              fontSize: 14,
                              fontWeight: FontWeight.w600,
                            ),
                          ),
                          SizedBox(height: 2),
                          Text(
                            '기준 날짜(첫 번째 날짜)와 같은 요일로 날짜를 자동으로 추가해요.',
                            style: TextStyle(fontSize: 12, color: Colors.black45),
                          ),
                        ],
                      ),
                    ),
                    Switch(
                      value: _weeklyRepeatEnabled,
                      onChanged: _toggleWeeklyRepeat,
                      activeThumbColor: _kAccent,
                    ),
                  ],
                ),
                if (_weeklyRepeatEnabled) ...[
                  const SizedBox(height: 10),
                  Row(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Expanded(
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            _label('반복 종료일 (선택)'),
                            _box(
                              _weeklyRepeatEndDate != null
                                  ? formatPartyDate(_weeklyRepeatEndDate)
                                  : '종료일 선택',
                              _pickWeeklyEndDate,
                              hasValue: _weeklyRepeatEndDate != null,
                            ),
                          ],
                        ),
                      ),
                      const SizedBox(width: 10),
                      Expanded(
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            _label('반복 횟수 (선택)'),
                            TextField(
                              controller: _repeatCountController,
                              keyboardType: TextInputType.number,
                              onChanged: _onRepeatCountChanged,
                              decoration: InputDecoration(
                                hintText: '예: 4',
                                suffixText: '회',
                                filled: true,
                                fillColor: _kBoxFill,
                                contentPadding: const EdgeInsets.symmetric(
                                  horizontal: 14,
                                  vertical: 14,
                                ),
                                border: OutlineInputBorder(
                                  borderRadius: BorderRadius.circular(12),
                                  borderSide: BorderSide.none,
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                  const SizedBox(height: 6),
                  if (_weeklyRepeatEndDate == null && _weeklyRepeatCount == null)
                    const Text(
                      '반복 종료일 또는 반복 횟수를 입력하면 자동으로 날짜가 추가돼요.',
                      style: TextStyle(fontSize: 12, color: Colors.black45),
                    )
                  else
                    Row(
                      children: [
                        const Expanded(
                          child: Text(
                            '최대 52회까지 자동 생성돼요.',
                            style: TextStyle(fontSize: 12, color: Colors.black45),
                          ),
                        ),
                        if (_weeklyRepeatEndDate != null)
                          TextButton(
                            onPressed: _clearWeeklyEndDate,
                            style: TextButton.styleFrom(
                              padding: EdgeInsets.zero,
                              minimumSize: const Size(0, 0),
                              tapTargetSize: MaterialTapTargetSize.shrinkWrap,
                            ),
                            child: const Text(
                              '종료일 지우기',
                              style: TextStyle(fontSize: 12),
                            ),
                          ),
                      ],
                    ),
                ],
                const SizedBox(height: 20),
                Row(
                  children: [
                    Expanded(child: _label('모집마감시간 (선택)')),
                    if (hasDeadline)
                      IconButton(
                        onPressed: _clearDeadline,
                        icon: const Icon(Icons.clear, size: 18),
                        color: Colors.black38,
                        padding: EdgeInsets.zero,
                        constraints: const BoxConstraints(),
                      ),
                  ],
                ),
                _box(
                  formatPartyTime(_recruitDeadlineTime),
                  _pickRecruitDeadlineTime,
                  hasValue: _recruitDeadlineTime != null,
                ),
                const SizedBox(height: 6),
                const Text(
                  '설정 시 각 날짜의 마감시간 이후 자동으로 신청 불가 처리됩니다.',
                  style: TextStyle(fontSize: 12, color: Colors.black45),
                ),
                const SizedBox(height: 20),
                SizedBox(
                  width: double.infinity,
                  height: 50,
                  child: ElevatedButton(
                    onPressed: () => Navigator.pop(
                      context,
                      PartyDateListDraft(
                        slots: _slots,
                        recruitDeadlineTime: _recruitDeadlineTime,
                        weeklyRepeatEnabled: _weeklyRepeatEnabled,
                        weeklyRepeatEndDate: _weeklyRepeatEndDate,
                        weeklyRepeatCount: _weeklyRepeatCount,
                        weeklyRepeatExcludedDates: _weeklyRepeatExcludedDates,
                      ),
                    ),
                    style: ElevatedButton.styleFrom(
                      backgroundColor: _kAccent,
                      foregroundColor: Colors.white,
                      shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(14),
                      ),
                    ),
                    child: const Text(
                      '선택 완료',
                      style: TextStyle(fontSize: 15, fontWeight: FontWeight.bold),
                    ),
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
